# Name of your application. Used to uniquely configure containers.
service: my-app

# Name of the container image.
image: abdulahadazam/my-app

# Deploy to these servers.
servers:
  web:
    - localhost

# SSH options
ssh:
  user: amrood

# Disable SSL (set to false as requested)
proxy:
  ssl: false
  host: localhost

# Credentials for Docker Hub
registry:
  username: abdulahadazam
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  context: "."
  dockerfile: "Dockerfile"
  args:
    RAILS_MASTER_KEY: <%= ENV['RAILS_MASTER_KEY'] %>

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - GMAIL_USERNAME
    - GMAIL_PASSWORD
    - STRIPE_PUBLISHABLE_KEY
    - STRIPE_SECRET_KEY
    - STRIPE_WEBHOOK_SECRET
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET

# Use a persistent storage volume.
volumes:
  - "app_storage:/app/storage"